language: julia

julia:
  - 1.0

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y sass

install:
  - https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

stages:
  - build
  - compile
  - name: deploy
    if: branch=master

jobs:
  include:
    - stage: build
      script: julia compile.jl
    - stage: compile
      script: hugo
