language: julia

julia:
  - 1.0

addons:
  apt:
    update: true

before_install:
  - gem install sass

install:
  - https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

stages:
  - build
  - compile
  - name: deploy
    if: branch=master

jobs:
  include:
    - stage: build
      script: julia compile.jl
    - stage: compile
      script: hugo
    - stage: deploy
      script: |
        if [ -n "$GITHUB_API_KEY" ]; then
        git checkout --orphan master
        git rm -rf .
        mv public/* .
        rm -rf public hugo_*
        git add -f --ignore-errors --all
        git -c user.name='travis' -c user.email='travis' commit -m init
        git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG master
        fi
