title: Scientific computing
subtitle: (for the rest of us)
permalink: pretty
exclude: ["_lessons/*.Jmd"]
markdown: kramdown

github: https://github.com/tpoisot/ScientificComputingForTheRestOfUs

collections:
  lessons:
    output: true
  capstones:
    output: true
