title: Scientific computing
subtitle: (for the rest of us)
permalink: pretty
exclude: ["*.Jmd"]
markdown: kramdown

readingspeed: 120
# Number of words per minute (lowered from the usual 180, because of technical content)

sass:
  style: :compressed
  sass_dir: _scss

palette: scru
# Can be teal (and that's it for now)

github: https://github.com/tpoisot/ScientificComputingForTheRestOfUs

collections:
  lessons:
    output: true
  capstones:
    output: true
