title: Scientific computing
subtitle: (for the rest of us)
permalink: pretty
exclude: ["*.Jmd"]
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _scss

palette: teal
# Can be teal (and that's it for now)

github: https://github.com/tpoisot/ScientificComputingForTheRestOfUs

collections:
  lessons:
    output: true
  capstones:
    output: true
