baseURL = "http://sciencecomputing.io/"
languageCode = "en-us"
preserveTaxonomyNames = true
theme = "shebang"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  readingSpeed = 120
  githubUser = "tpoisot"
  githubRepo = "ScientificComputingForTheRestOfUs"
  title = "Scientific computing"
  subtitle = "(for the rest of us)"

[taxonomies]
  concept = "concepts"
  package = "packages"
